Update lock. Uncomment hooks. Remove ioS dev team.

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -2,22 +2,22 @@
 
 check_error="Git hook check error"
 
-## Check if there are any local dependencies in the pubspec.yaml file
-#local_deps=$(grep -E "path:.*" pubspec.yaml)
-#
-## If local dependencies are found, exit with an error message
-#if [ "$local_deps" ]; then
-#  echo "$check_error: Local dependencies found in pubspec.yaml: \n\n $local_deps \n\n Push blocked to prevent committing local dependencies."
-#  exit 1
-#fi
+# Check if there are any local dependencies in the pubspec.yaml file
+local_deps=$(grep -E "path:.*" pubspec.yaml)
+
+# If local dependencies are found, exit with an error message
+if [ "$local_deps" ]; then
+  echo "$check_error: Local dependencies found in pubspec.yaml: \n\n $local_deps \n\n Push blocked to prevent committing local dependencies."
+  exit 1
+fi
 
 # Check if there are any Github dependencies in the pubspec.yaml file
 github_deps=$(grep -E "https://github.com" pubspec.yaml)
 
 # If github dependencies are found, exit with an error message
 if [ "$github_deps" ]; then
- echo "$check_error: Github dependencies found in pubspec.yaml: \n\n $github_deps \n\n Push blocked to prevent committing Github dependencies."
- exit 1
+  echo "$check_error: Github dependencies found in pubspec.yaml: \n\n $github_deps \n\n Push blocked to prevent committing Github dependencies."
+  exit 1
 fi
 
 # Check if publishable key is set in  main.dart
@@ -25,14 +25,14 @@ fi
 LENGTH=$(grep -o '_publishableKey = .*' lib/main.dart | cut -d'"' -f2 | wc -c | awk '{$1=$1-1}1')
 
 if [ $LENGTH -eq 86 ]; then
- echo "$check_error: _publishableKey is set"
- exit 1
+  echo "$check_error: _publishableKey is set"
+  exit 1
 fi
 
 xcode_project_config_path="ios/Runner.xcodeproj/project.pbxproj"
 
 # Check if the xcodeproj command line tool is installed
-if ! type "xcodeproj" > /dev/null; then
+if ! type "xcodeproj" >/dev/null; then
   echo "$check_error: The xcodeproj command line tool is not installed. Unable to check if the development team is set up."
 else
   # Check if the project file exists
