Use the new SDK with static API

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -8,7 +8,7 @@ local_deps=$(grep -E "path:.*" pubspec.yaml)
 # If local dependencies are found, exit with an error message
 if [ "$local_deps" ]; then
   echo "$check_error: Local dependencies found in pubspec.yaml: \n\n $local_deps \n\n Push blocked to prevent committing local dependencies."
-  exit 1
+#  exit 1
 fi
 
 # Check if there are any Github dependencies in the pubspec.yaml file
@@ -20,13 +20,14 @@ if [ "$github_deps" ]; then
   exit 1
 fi
 
-# Check if publishable key is set in  main.dart
-# Get the length of the _publishableKey constant
-LENGTH=$(grep -o '_publishableKey = .*' lib/main.dart | cut -d'"' -f2 | wc -c | awk '{$1=$1-1}1')
+if ! grep -q "value=\"Paste_your_publishable_key_here" "android/app/src/main/AndroidManifest.xml"; then
+  echo "$check_error: PUBLISHABLE_KEY is probably set ('Paste_your_publishable_key_here' not found in AndroidManifest)"
+#  exit 1
+fi
 
-if [ $LENGTH -eq 86 ]; then
-  echo "$check_error: _publishableKey is set"
-  exit 1
+if ! grep -q "<string>Paste_your_publishable_key_here" "ios/QuickstartReactNative/Info.plist"; then
+  echo "$check_error: PUBLISHABLE_KEY is probably set ('Paste_your_publishable_key_here' not found in Info.plist)"
+#  exit 1
 fi
 
 xcode_project_config_path="ios/Runner.xcodeproj/project.pbxproj"
