Comment out hook

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -2,14 +2,14 @@
 
 check_error="Git hook check error"
 
-# Check if there are any local dependencies in the pubspec.yaml file
-local_deps=$(grep -E "path:.*" pubspec.yaml)
-
-# If local dependencies are found, exit with an error message
-if [ "$local_deps" ]; then
-  echo "$check_error: Local dependencies found in pubspec.yaml: \n\n $local_deps \n\n Push blocked to prevent committing local dependencies."
-  exit 1
-fi
+## Check if there are any local dependencies in the pubspec.yaml file
+#local_deps=$(grep -E "path:.*" pubspec.yaml)
+#
+## If local dependencies are found, exit with an error message
+#if [ "$local_deps" ]; then
+#  echo "$check_error: Local dependencies found in pubspec.yaml: \n\n $local_deps \n\n Push blocked to prevent committing local dependencies."
+#  exit 1
+#fi
 
 # Check if there are any Github dependencies in the pubspec.yaml file
 github_deps=$(grep -E "https://github.com" pubspec.yaml)
